ror_app_form/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # form at root
  get '/', to: 'nodes#new', as: 'new_node'
  post '/', to: 'nodes#create', as: 'create_node'

  get '/download', to: 'nodes#download'

end

ror_app_form/app/models/node.rb
# validate IPv4
require 'ipaddress'

class Node
  include ActiveModel::Model
  attr_accessor :device, :node_name, :wifi_channel, :bmx6_tun4, :vars
  validates :device, :node_name, :wifi_channel, :bmx6_tun4, presence: true

  # src https://medium.com/@rfleury2/a-quick-guide-to-model-errors-in-rails-965e2be3ac93
  validates_numericality_of :wifi_channel
  validate :validate_ip_address

  private

  # custom validation -> https://hackernoon.com/performing-custom-validations-in-rails-an-example-9a373e807144
  def validate_ip_address
    addr = bmx6_tun4
    ip, netmask = addr.split("/")

    unless IPAddress.valid_ipv4?(ip) && (!(netmask =~ /\A([12]?\d|3[0-2])\z/).nil? || IPAddress.valid_ipv4_netmask?(netmask))
    # TODO Need newer version of gem -> src https://github.com/ipaddress-gem/ipaddress/blob/master/lib/ipaddress.rb#L157-L161
    #unless IPAddress.valid_ipv4_subnet? addr
      errors.add(:bmx6_tun4, 'IP address invalid. Example: 10.0.0.1/27')
    end
  end
end

ror_app_form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ror_app_form/app/controllers/nodes_controller.rb
load '../tembalib.rb'

class NodesController < ApplicationController
  def new
    @node = Node.new
    @node.vars = read_vars('../') # load config for form
  end

  # thanks https://stackoverflow.com/questions/22002020/how-to-download-file-with-send-file
  def download
    # are you blacklisting? -> https://guides.rubyonrails.org/security.html#file-uploads
    @download_params = params.require(:file)
    file_name = params['file'].split('/').last
    download = params['download']
    file_loc = "#{Rails.root}/../output/#{file_name}"
    if File.exists? file_loc
      if download == 'true'
        return send_file file_loc
      end
      # src https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-text
      return render plain: "/download?file=#{file_name}&download=true"
    else
      return render plain: 'not available'
    end

  end

  def create
    @node = Node.new node_params
    @node.vars = read_vars('../') # load config for the procedure of building firmware

    if @node.valid?

      target = @node.device
      device = @node.vars['devices'][target]
      device['node_name'] = @node.node_name
      device['wifi_channel'] = @node.wifi_channel
      device['bmx6_tun4'] = @node.bmx6_tun4

      device['timestamp'] = gen_timestamp()

      # Use thread pool as compilation process must be on at a time
      # To enqueue a job to be performed as soon as the queueing system is free:
      CompileJob.perform_later(device)

      # src https://stackoverflow.com/a/8420078
      redirect_to new_node_url, notice: "Petition received to build node: #{device['node_name']}_#{device['timestamp']}"

    else

      # render page again with the entered values
      render :new

    end
  end

  # Only public methods are callable as actions. It is a best practice to lower the visibility of methods (with private or protected) which are not intended to be actions, like auxiliary methods or filters. -> src https://guides.rubyonrails.org/action_controller_overview.html#methods-and-actions
  private

  def node_params
    # strong parameters -> https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters
    return params.require(:node).permit(:device, :node_name, :wifi_channel, :bmx6_tun4)
  end
end

ror_app_form/app/helpers/application_helper.rb
module ApplicationHelper
end

ror_app_form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorAppForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ror_app_form/app/views/nodes/new.html.erb
<p>Other users online: <span id="online_users"></span></p>
<h1>generate a temba node</h1>
<%# be inspired by this form: https://github.com/jirutka/ldap-passwd-webui %>
<%= form_for @node, url: create_node_url do |f| %>

  <%# src https://stackoverflow.com/a/3873520 %>
  <% if @node.errors.any? %>
    Errors:
    <ul>
    <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>

  <% end %>

  <%# options_for_select -> src https://stackoverflow.com/questions/19120706/rails-erb-form-helper-options-for-select-selected %>
  <%# this form is not prepared for border templates -> src https://stackoverflow.com/a/7085390 %>
  <%# retain select values after error:
    https://stackoverflow.com/questions/26872093/rails-4-retaining-form-values-on-refresh
    https://stackoverflow.com/questions/5052889/ruby-on-rails-f-select-options-with-custom-attributes
  %>
  <%= f.select :device, options_for_select(@node.vars['devices'].reject{|k| k=~ /border/}.each_key, f.object.device), :prompt => 'select device' %>
  <%= f.text_field :node_name, placeholder: 'node name' %>
  <%# f.text_field :wifi_channel, placeholder: 'wifi channel' %>
  <%# TODO: yaml variable valid channels or target channels ? %>
  <%# f.select :wifi_channel, options_for_select([120, 132]), :prompt => 'wifi channel' %>
  <%= f.select :wifi_channel, options_for_select([36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161, 165], f.object.wifi_channel), :prompt => 'wifi channel' %>

  <%= f.text_field :bmx6_tun4, placeholder: 'IPv4' %>
  <%= f.submit 'Build' %>
  <br>
  <div class="loader"></div>
  <%# https://stackoverflow.com/questions/42535407/render-html-into-rails-flash-message %>
  <%# https://stackoverflow.com/questions/24334755/form-undefined-method-html-safe-for-nilnilclass %>
  <p id="notice"><%= notice %></p>

<% end %>

<p class="footer">
  <%= @node.vars['temba_version'] %> |
  <a href="https://gitlab.com/guifi-exo/temba/issues" target="_blank"><b>Issues</b></a> |
  <a href="https://gitlab.com/guifi-exo/temba" target="_blank">Source Code</a> |
  Contribute to <a href="https://gitlab.com/guifi-exo/temba/tree/master/files" target="_blank">templates</a>!
</p>